### ISSUE TITLE
library not found on macOS

### ISSUE THREAD

**Issue by ingmarschuster** [rofuyu/exp-trmf-nips16#3]
Hi, and thanks a lot for making your code available. On macOS when following your instructions, it doesn't find the libraries built with ```CC=gcc-8 CXx=g++-8 pip install .```
```
~/Documents/university/Promotion_NLP/software/python/exp-trmf-nips16/python/exp-scripts/trmf/trmf.py in __init__(self, dirname, soname, forced_rebuild)
     19 class corelib(object):
     20     def __init__(self, dirname, soname, forced_rebuild=False):
---> 21         self.clib_float32 = load_dynamic_library(dirname, soname + '_float32', forced_rebuild=forced_rebuild)
     22         self.clib_float64 = load_dynamic_library(dirname, soname + '_float64', forced_rebuild=forced_rebuild)
     23         arg_list = [

~/Documents/university/Promotion_NLP/software/python/exp-trmf-nips16/python/exp-scripts/trmf/rf_util.py in load_dynamic_library(dirname, soname, forced_rebuild)
     30             _c_lib = CDLL(path_to_so)
     31         except :
---> 32             raise Exception('{soname} library cannot be found and built.'.format(soname=soname))
     33     return _c_lib
     34

Exception: trmf_float32 library cannot be found and built.
```

**Comment by mmaddukuri-cs** [comment]
I got the same error on macOS. Have you figured out the fix?

**Comment by mmaddukuri-cs** [comment]
> Hi, and thanks a lot for making your code available. On macOS when following your instructions, it doesn't find the libraries built with `CC=gcc-8 CXx=g++-8 pip install .`
> 
> ```
> ~/Documents/university/Promotion_NLP/software/python/exp-trmf-nips16/python/exp-scripts/trmf/trmf.py in __init__(self, dirname, soname, forced_rebuild)
>      19 class corelib(object):
>      20     def __init__(self, dirname, soname, forced_rebuild=False):
> ---> 21         self.clib_float32 = load_dynamic_library(dirname, soname + '_float32', forced_rebuild=forced_rebuild)
>      22         self.clib_float64 = load_dynamic_library(dirname, soname + '_float64', forced_rebuild=forced_rebuild)
>      23         arg_list = [
> 
> ~/Documents/university/Promotion_NLP/software/python/exp-trmf-nips16/python/exp-scripts/trmf/rf_util.py in load_dynamic_library(dirname, soname, forced_rebuild)
>      30             _c_lib = CDLL(path_to_so)
>      31         except :
> ---> 32             raise Exception('{soname} library cannot be found and built.'.format(soname=soname))
>      33     return _c_lib
>      34
> 
> Exception: trmf_float32 library cannot be found and built.
> ```

I got the same error on macOS. Have you figured out the fix?

**Comment by rofuyu** [comment]
There is typo in the MacOS section in the README, which is fixed now. 
Instead of 
`CC=gcc-8 CXx=g++-8 pip install .` 
we need
`CC=gcc-8 CXX=g++-8 pip install -e .`

Please open it if it does not resolve the problem.
