### ISSUE TITLE
No data to test

### ISSUE THREAD

**Issue by Molesox** [rofuyu/exp-trmf-nips16#4]
Hello,
In the readme, it says to see the folder data where we should find electricity and traffic datasets. However, I don't see anything. The code is hard enough so it would be nice if I could try a "hello world" example to start. thanks :)

**Comment by rofuyu** [comment]
You can download the data by running the script https://github.com/rofuyu/exp-trmf-nips16/blob/master/python/exp-scripts/datasets/download-data.sh
