### ISSUE TITLE
error when downloading the datasets

### ISSUE THREAD

**Issue by hihihihiwsf** [rofuyu/exp-trmf-nips16#5]
![image](https://user-images.githubusercontent.com/33193751/64005696-748a9f80-cb43-11e9-94ab-12b349c7fd99.png)
Can you help me with this?

**Comment by abalhomaid** [comment]
hi,

you can download the datasets manually using the ids in download-data.sh

for example, if you'd like to download the following files, type the following on your browser

traffic.npy
https://drive.google.com/uc?export=download&id=1R_M3RP-t5CKDj5gUVTU2IEZXDInQKHJG

electricity.npy
https://drive.google.com/uc?export=download&id=1uJDqW4u2shjbA_Y27oIcq-QM2jgW4c9g

**Comment by rofuyu** [comment]
Thanks @abalhomaid for the response. Closing the issue.
